language: java
sudo: true
jdk:
  - oraclejdk8
services: mysql
before_install:
  - 'mysql -e ''create database craftconomy;'''
script:
  - './gradlew -Dmysql=true && ./gradlew'
after_success:
  - 'ls /home/travis/build/Neder/craftconomy3'
