language: java
sudo: false
jdk:
- oraclejdk8
services: mysql
before_install:
- mysql -e 'create database craftconomy;'
script: ./gradlew -Dmysql=true && ./gradlew
after_success:
- 'tree /home/travis/Neder/craftconomy3'
