language: java
jdk:
  - oraclejdk8
services: mysql
before_install:
  - 'mysql -e ''create database craftconomy;'''
script:
  - './gradlew -Dmysql=true'
after_success:
  - 'ls /home/travis/build/Neder/craftconomy3'
  - 'tar -cvzf craftconomy_${TRAVIS_JOB_NUMBER}.tar.gz *'
  - 'sudo chmod 777 ./upload.sh'
  - './upload.sh'
